---
- name: Удалить старые версии Docker
  apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
    autoremove: yes
    purge: yes

- name: Установить зависимости
  apt:
    name:
      - ca-certificates
      - curl
      - gnupg
    state: present
    update_cache: yes

- name: Создать директорию для ключей APT
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Скачать GPG-ключ Docker
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
    force: yes

- name: Определить кодовое имя ОС
  set_fact:
    ubuntu_codename: "{{ ansible_lsb.codename if ansible_lsb.codename is defined else ansible_distribution_release }}"

- name: Добавить репозиторий Docker
  lineinfile:
    path: /etc/apt/sources.list.d/docker.list
    line: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ubuntu_codename }} stable"
    create: yes
    state: present

- name: Обновить кэш пакетов
  apt:
    update_cache: yes

- name: Установить Docker CE и плагины
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present